version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "10:00"
      timezone: Europe/Berlin
    allow:
      - dependency-name: "*"
        dependency-type: "production"
    open-pull-requests-limit: 2
    reviewers:
      - art333
      - segfault79
      - bwagneras
      - andrespringt
      - daniel-krug
      - Tooobi
