name: Checks
on:
  pull_request:
  # we're doing the filtering for branches and actions in each step,
  # this one here works not as expected and could be misleading
#    branches:
#      - migrating-to-yaml-syntax
#      - master
#    action:
#      - opened
#      - edited
#      - synchronize
jobs:
  checks:
    name: Formatting checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        if: github.event.action == 'opened' || github.event.action == 'edited' || github.event.action == 'synchronize'
        uses: actions/checkout@v1.2.0

      - name: Set Node.js 16
        if: github.event.action == 'opened' || github.event.action == 'edited' || github.event.action == 'synchronize'
        uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Install npm
        if: github.event.action == 'opened' || github.event.action == 'edited' || github.event.action == 'synchronize'
        run: npm ci

      - name: Npm format-check
        if: github.event.action == 'opened' || github.event.action == 'edited' || github.event.action == 'synchronize'
        run: npm run check

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        if: github.event.action == 'opened' || github.event.action == 'edited' || github.event.action == 'synchronize'
        uses: actions/checkout@v1.2.0

      - name: Checkout master
        if: github.event.action == 'opened' || github.event.action == 'edited' || github.event.action == 'synchronize'
        uses: actions/checkout@v1.2.0
        with:
          ref: master

      - name: Check merge
        if: github.event.action == 'opened' || github.event.action == 'edited' || github.event.action == 'synchronize'
        run: |
          git config --global user.name "Spring Media CD"
          git config --global user.email "ps-support-og@moveoffice.com"
          git merge ${{ github.event.pull_request.head.sha }} -m"prchecker" --stat

      - name: Set Node.js 16
        if: github.event.action == 'opened' || github.event.action == 'edited' || github.event.action == 'synchronize'
        uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Install npm
        if: github.event.action == 'opened' || github.event.action == 'edited' || github.event.action == 'synchronize'
        run: npm ci

      - name: Test npm
        if: github.event.action == 'opened' || github.event.action == 'edited' || github.event.action == 'synchronize'
        run: npm run test

      - name: Build npm
        if: github.event.action == 'opened' || github.event.action == 'edited' || github.event.action == 'synchronize'
        run: npm run build
