name: Checks
on:
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.PS_GITHUB_ACCESSTOKEN }}

jobs:
  checks:
    name: Formatting checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Set Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: "16"
          cache: 'yarn'

      - name: Configure npm
        run: |
          npm config set //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN

      - name: Install yarn
        run: yarn install --frozen-lockfile

      - name: yarn format-check
        run: yarn check

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Set Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: "16"
          cache: 'yarn'

      - name: Configure npm
        run: |
          npm config set //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN

      - name: Install yarn
        run: yarn install --frozen-lockfile

      - name: Test yarn
        run: yarn test

      - name: Build yarn
        run: yarn build
